version: "3"

services:
  login_google:
    container_name: login_google
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
