from setuptools import setup, find_packages

setup(
    name='wow_django_test_package',
    version='0.0.1',
    install_requires=[
        "cffi==1.15.1",
        "charset-normalizer==3.0.1",
        "cryptography==39.0.1",
        "defusedxml==0.7.1",
        "django-allauth==0.52.0",
        "idna==3.4",
        "oauthlib==3.2.2",
        "pycparser==2.21",
        "PyJWT==2.6.0",
        "python3-openid==3.2.0",
        "requests==2.28.2",
        "requests-oauthlib==1.3.1",
        "urllib3==1.26.14",
        "django~=4.1",
        "djangogrpcframework==0.2.1",
        "djangorestframework==3.14.0",
        "grpcio==1.51.3",
        "grpcio-tools==1.51.3",
    ],
    author='truongnv',
    author_email='truongnguyenvan0590@gmail.com',
    description='test project write in django',
    url='https://github.com/truongnv90/singleSignOn',
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: APACHE License",
        "Operating System :: OS Independent",
    ],
    package_dir={"": "."},
    packages=find_packages(where="."),
    python_requires=">=3.8",
    scripts=["manage.py"],
)
